In [60]:
import numpy as np
import pandas as pd
import random

def ratelist(total, rate):
    li = []

    o = 1
    x = 0

    _rate = rate
    _count = total

    for i in range(1,_count):
        if i <= _rate * _count:
            li.append(o)
        else:
            li.append(x)
    
    random.shuffle(li)
    return li

In [61]:
HF01 = ratelist(1001, 0.000) # 간
HF02 = ratelist(1001, 0.000) # 피로
HF03 = ratelist(1001, 0.000) # 뼈/관절
HF04 = ratelist(1001, 0.100) # 치아/구강
HF05 = ratelist(1001, 0.000) # 면역
HF06 = ratelist(1001, 0.000) # 노화/항산화
HF07 = ratelist(1001, 0.200) # 피부
HF08 = ratelist(1001, 0.000) # 눈
HF09 = ratelist(1001, 0.000) # 위/소화
HF10 = ratelist(1001, 0.500) # 장건강
HF11 = ratelist(1001, 0.000) # 비뇨
HF12 = ratelist(1001, 0.000) # 요로
HF13 = ratelist(1001, 0.000) # 전립선
HF14 = ratelist(1001, 0.000) # 남성
HF15 = ratelist(1001, 0.000) # 여성 갱년기
HF16 = ratelist(1001, 0.000) # 여성
HF17 = ratelist(1001, 0.000) # 운동
HF18 = ratelist(1001, 0.000) # 체지방
HF19 = ratelist(1001, 0.000) # 스트레스/수면
HF20 = ratelist(1001, 0.500) # 두뇌
HF21 = ratelist(1001, 0.800) # 어린이 성장
HF22 = ratelist(1001, 0.000) # 혈당
HF23 = ratelist(1001, 0.000) # 혈압
HF24 = ratelist(1001, 0.000) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.005) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.013) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.010) # 위장관
DI02 = ratelist(1001, 0.010) # 간
DI03 = ratelist(1001, 0.010) # 심혈관계
DI04 = ratelist(1001, 0.010) # 신장
DI05 = ratelist(1001, 0.005) # 당뇨
DI06 = ratelist(1001, 0.010) # 고혈압
DI07 = ratelist(1001, 0.010) # 고지혈증
DI08 = ratelist(1001, 0.000) # 혈액응고장애
DI09 = ratelist(1001, 0.010) # 갑상선
DI10 = ratelist(1001, 0.010) # 천식
DI11 = ratelist(1001, 0.005) # 담낭
DI12 = ratelist(1001, 0.010) # 자가면역
DI13 = ratelist(1001, 0.010) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.010) # 수술 여부
survey_alcohol = ratelist(1001, 0.000)   # 음주 여부
survey_smoking = ratelist(1001, 0.000)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(00)
    survey_sex.append(0)

M_00 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_00

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
HF01 = ratelist(1001, 0.000) # 간
HF02 = ratelist(1001, 0.000) # 피로
HF03 = ratelist(1001, 0.000) # 뼈/관절
HF04 = ratelist(1001, 0.050) # 치아/구강
HF05 = ratelist(1001, 0.000) # 면역
HF06 = ratelist(1001, 0.000) # 노화/항산화
HF07 = ratelist(1001, 0.200) # 피부
HF08 = ratelist(1001, 0.000) # 눈
HF09 = ratelist(1001, 0.000) # 위/소화
HF10 = ratelist(1001, 0.500) # 장건강
HF11 = ratelist(1001, 0.000) # 비뇨
HF12 = ratelist(1001, 0.000) # 요로
HF13 = ratelist(1001, 0.000) # 전립선
HF14 = ratelist(1001, 0.000) # 남성
HF15 = ratelist(1001, 0.000) # 여성 갱년기
HF16 = ratelist(1001, 0.000) # 여성
HF17 = ratelist(1001, 0.100) # 운동
HF18 = ratelist(1001, 0.100) # 체지방
HF19 = ratelist(1001, 0.100) # 스트레스/수면
HF20 = ratelist(1001, 0.700) # 두뇌
HF21 = ratelist(1001, 0.100) # 어린이 성장
HF22 = ratelist(1001, 0.000) # 혈당
HF23 = ratelist(1001, 0.000) # 혈압
HF24 = ratelist(1001, 0.000) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.005) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.013) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.010) # 위장관
DI02 = ratelist(1001, 0.010) # 간
DI03 = ratelist(1001, 0.010) # 심혈관계
DI04 = ratelist(1001, 0.010) # 신장
DI05 = ratelist(1001, 0.005) # 당뇨
DI06 = ratelist(1001, 0.010) # 고혈압
DI07 = ratelist(1001, 0.010) # 고지혈증
DI08 = ratelist(1001, 0.000) # 혈액응고장애
DI09 = ratelist(1001, 0.010) # 갑상선
DI10 = ratelist(1001, 0.010) # 천식
DI11 = ratelist(1001, 0.005) # 담낭
DI12 = ratelist(1001, 0.010) # 자가면역
DI13 = ratelist(1001, 0.010) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.010) # 수술 여부
survey_alcohol = ratelist(1001, 0.000)   # 음주 여부
survey_smoking = ratelist(1001, 0.000)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(10)
    survey_sex.append(0)

M_10 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_10

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [63]:
HF01 = ratelist(1001, 0.198*0.15) # 간
HF02 = ratelist(1001, 0.420*0.698) # 피로
HF03 = ratelist(1001, 0.000*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.098*0.023) # 치아/구강
HF05 = ratelist(1001, 0.132*1) # 면역
HF06 = ratelist(1001, 0.082*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.360*0.268) # 피부
HF08 = ratelist(1001, 0.000*0.265) # 눈
HF09 = ratelist(1001, 0.084*0.008) # 위/소화
HF10 = ratelist(1001, 0.265*0.322) # 장건강
HF11 = ratelist(1001, 0.074*0.005) # 비뇨
HF12 = ratelist(1001, 0.016*0.005) # 요로
HF13 = ratelist(1001, 0.000*0.031) # 전립선
HF14 = ratelist(1001, 0.000*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.000*0.407) # 여성
HF17 = ratelist(1001, 0.406*0.465) # 운동
HF18 = ratelist(1001, 0.400*0.188) # 체지방
HF19 = ratelist(1001, 0.341*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.006*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.004*0.058) # 혈당
HF23 = ratelist(1001, 0.039*0.037) # 혈압
HF24 = ratelist(1001, 0.034*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.265) # 위장관
DI02 = ratelist(1001, 0.198) # 간
DI03 = ratelist(1001, 0.039) # 심혈관계
DI04 = ratelist(1001, 0.010) # 신장
DI05 = ratelist(1001, 0.004) # 당뇨
DI06 = ratelist(1001, 0.039) # 고혈압
DI07 = ratelist(1001, 0.034) # 고지혈증
DI08 = ratelist(1001, 0.000) # 혈액응고장애
DI09 = ratelist(1001, 0.022) # 갑상선
DI10 = ratelist(1001, 0.023) # 천식
DI11 = ratelist(1001, 0.004) # 담낭
DI12 = ratelist(1001, 0.009) # 자가면역
DI13 = ratelist(1001, 0.109) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.009) # 수술 여부
survey_alcohol = ratelist(1001, 0.631)   # 음주 여부
survey_smoking = ratelist(1001, 0.376)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(20)
    survey_sex.append(0)

M_20 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_20

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,20,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,20,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,20,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,20,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,20,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [64]:
HF01 = ratelist(1001, 0.238*0.15) # 간
HF02 = ratelist(1001, 0.491*0.698) # 피로
HF03 = ratelist(1001, 0.000*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.088*0.023) # 치아/구강
HF05 = ratelist(1001, 0.243*1) # 면역
HF06 = ratelist(1001, 0.148*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.336*0.268) # 피부
HF08 = ratelist(1001, 0.037*0.265) # 눈
HF09 = ratelist(1001, 0.120*0.008) # 위/소화
HF10 = ratelist(1001, 0.260*0.322) # 장건강
HF11 = ratelist(1001, 0.088*0.005) # 비뇨
HF12 = ratelist(1001, 0.016*0.005) # 요로
HF13 = ratelist(1001, 0.105*0.031) # 전립선
HF14 = ratelist(1001, 0.020*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.000*0.407) # 여성
HF17 = ratelist(1001, 0.352*0.465) # 운동
HF18 = ratelist(1001, 0.412*0.188) # 체지방
HF19 = ratelist(1001, 0.345*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.029*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.050*0.058) # 혈당
HF23 = ratelist(1001, 0.173*0.037) # 혈압
HF24 = ratelist(1001, 0.186*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.260) # 위장관
DI02 = ratelist(1001, 0.238) # 간
DI03 = ratelist(1001, 0.173) # 심혈관계
DI04 = ratelist(1001, 0.044) # 신장
DI05 = ratelist(1001, 0.050) # 당뇨
DI06 = ratelist(1001, 0.173) # 고혈압
DI07 = ratelist(1001, 0.186) # 고지혈증
DI08 = ratelist(1001, 0.003) # 혈액응고장애
DI09 = ratelist(1001, 0.017) # 갑상선
DI10 = ratelist(1001, 0.050) # 천식
DI11 = ratelist(1001, 0.010) # 담낭
DI12 = ratelist(1001, 0.009) # 자가면역
DI13 = ratelist(1001, 0.079) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.013) # 수술 여부
survey_alcohol = ratelist(1001, 0.691)   # 음주 여부
survey_smoking = ratelist(1001, 0.389)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(30)
    survey_sex.append(0)

M_30 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_30

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,30,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
1,30,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,30,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,30,0,0,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,30,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,30,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,30,0,0,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
997,30,0,0,0,1,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
998,30,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [65]:
HF01 = ratelist(1001, 0.251*0.15) # 간
HF02 = ratelist(1001, 0.463*0.698) # 피로
HF03 = ratelist(1001, 0.045*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.071*0.023) # 치아/구강
HF05 = ratelist(1001, 0.238*1) # 면역
HF06 = ratelist(1001, 0.097*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.187*0.268) # 피부
HF08 = ratelist(1001, 0.155*0.265) # 눈
HF09 = ratelist(1001, 0.182*0.008) # 위/소화
HF10 = ratelist(1001, 0.227*0.322) # 장건강
HF11 = ratelist(1001, 0.104*0.005) # 비뇨
HF12 = ratelist(1001, 0.026*0.005) # 요로
HF13 = ratelist(1001, 0.212*0.031) # 전립선
HF14 = ratelist(1001, 0.024*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.000*0.407) # 여성
HF17 = ratelist(1001, 0.284*0.465) # 운동
HF18 = ratelist(1001, 0.445*0.188) # 체지방
HF19 = ratelist(1001, 0.382*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.160*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.143*0.058) # 혈당
HF23 = ratelist(1001, 0.257*0.037) # 혈압
HF24 = ratelist(1001, 0.269*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.260) # 위장관
DI02 = ratelist(1001, 0.238) # 간
DI03 = ratelist(1001, 0.173) # 심혈관계
DI04 = ratelist(1001, 0.044) # 신장
DI05 = ratelist(1001, 0.050) # 당뇨
DI06 = ratelist(1001, 0.173) # 고혈압
DI07 = ratelist(1001, 0.186) # 고지혈증
DI08 = ratelist(1001, 0.011) # 혈액응고장애
DI09 = ratelist(1001, 0.021) # 갑상선
DI10 = ratelist(1001, 0.023) # 천식
DI11 = ratelist(1001, 0.014) # 담낭
DI12 = ratelist(1001, 0.009) # 자가면역
DI13 = ratelist(1001, 0.104) # 신경/정신계
DI14 = ratelist(1001, 0.005) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.016) # 수술 여부
survey_alcohol = ratelist(1001, 0.748)   # 음주 여부
survey_smoking = ratelist(1001, 0.427)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(40)
    survey_sex.append(0)

M_40 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_40

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,40,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,40,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,40,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,40,0,0,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,40,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,40,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
996,40,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,40,0,0,1,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
998,40,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,40,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [66]:
HF01 = ratelist(1001, 0.245*0.15) # 간
HF02 = ratelist(1001, 0.362*0.698) # 피로
HF03 = ratelist(1001, 0.055*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.063*0.023) # 치아/구강
HF05 = ratelist(1001, 0.300*1) # 면역
HF06 = ratelist(1001, 0.136*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.204*0.268) # 피부
HF08 = ratelist(1001, 0.190*0.265) # 눈
HF09 = ratelist(1001, 0.203*0.008) # 위/소화
HF10 = ratelist(1001, 0.304*0.322) # 장건강
HF11 = ratelist(1001, 0.135*0.005) # 비뇨
HF12 = ratelist(1001, 0.031*0.005) # 요로
HF13 = ratelist(1001, 0.375*0.031) # 전립선
HF14 = ratelist(1001, 0.044*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.000*0.407) # 여성
HF17 = ratelist(1001, 0.313*0.465) # 운동
HF18 = ratelist(1001, 0.372*0.188) # 체지방
HF19 = ratelist(1001, 0.350*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.406*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.217*0.058) # 혈당
HF23 = ratelist(1001, 0.358*0.037) # 혈압
HF24 = ratelist(1001, 0.342*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.304) # 위장관
DI02 = ratelist(1001, 0.245) # 간
DI03 = ratelist(1001, 0.358) # 심혈관계
DI04 = ratelist(1001, 0.097) # 신장
DI05 = ratelist(1001, 0.217) # 당뇨
DI06 = ratelist(1001, 0.358) # 고혈압
DI07 = ratelist(1001, 0.342) # 고지혈증
DI08 = ratelist(1001, 0.026) # 혈액응고장애
DI09 = ratelist(1001, 0.030) # 갑상선
DI10 = ratelist(1001, 0.017) # 천식
DI11 = ratelist(1001, 0.025) # 담낭
DI12 = ratelist(1001, 0.016) # 자가면역
DI13 = ratelist(1001, 0.099) # 신경/정신계
DI14 = ratelist(1001, 0.005) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.028) # 수술 여부
survey_alcohol = ratelist(1001, 0.713)   # 음주 여부
survey_smoking = ratelist(1001, 0.369)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(50)
    survey_sex.append(0)

M_50 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_50

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,50,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,50,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,50,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,50,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,50,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,50,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,50,0,0,0,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,0
997,50,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,50,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,50,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [67]:
HF01 = ratelist(1001, 0.237*0.15) # 간
HF02 = ratelist(1001, 0.223*0.698) # 피로
HF03 = ratelist(1001, 0.200*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.053*0.023) # 치아/구강
HF05 = ratelist(1001, 0.348*1) # 면역
HF06 = ratelist(1001, 0.117*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.099*0.268) # 피부
HF08 = ratelist(1001, 0.270*0.265) # 눈
HF09 = ratelist(1001, 0.211*0.008) # 위/소화
HF10 = ratelist(1001, 0.279*0.322) # 장건강
HF11 = ratelist(1001, 0.217*0.005) # 비뇨
HF12 = ratelist(1001, 0.052*0.005) # 요로
HF13 = ratelist(1001, 0.538*0.031) # 전립선
HF14 = ratelist(1001, 0.213*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.000*0.407) # 여성
HF17 = ratelist(1001, 0.303*0.465) # 운동
HF18 = ratelist(1001, 0.364*0.188) # 체지방
HF19 = ratelist(1001, 0.339*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.636*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.288*0.058) # 혈당
HF23 = ratelist(1001, 0.506*0.037) # 혈압
HF24 = ratelist(1001, 0.332*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.279) # 위장관
DI02 = ratelist(1001, 0.237) # 간
DI03 = ratelist(1001, 0.506) # 심혈관계
DI04 = ratelist(1001, 0.255) # 신장
DI05 = ratelist(1001, 0.288) # 당뇨
DI06 = ratelist(1001, 0.506) # 고혈압
DI07 = ratelist(1001, 0.332) # 고지혈증
DI08 = ratelist(1001, 0.109) # 혈액응고장애
DI09 = ratelist(1001, 0.022) # 갑상선
DI10 = ratelist(1001, 0.029) # 천식
DI11 = ratelist(1001, 0.037) # 담낭
DI12 = ratelist(1001, 0.016) # 자가면역
DI13 = ratelist(1001, 0.074) # 신경/정신계
DI14 = ratelist(1001, 0.022) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.075) # 수술 여부
survey_alcohol = ratelist(1001, 0.667)   # 음주 여부
survey_smoking = ratelist(1001, 0.286)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(60)
    survey_sex.append(0)

M_60 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

M_60

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,60,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,60,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,60,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,60,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,60,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,60,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,60,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
997,60,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,60,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
999,60,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
HF01 = ratelist(1001, 0.000) # 간
HF02 = ratelist(1001, 0.000) # 피로
HF03 = ratelist(1001, 0.000) # 뼈/관절
HF04 = ratelist(1001, 0.100) # 치아/구강
HF05 = ratelist(1001, 0.000) # 면역
HF06 = ratelist(1001, 0.000) # 노화/항산화
HF07 = ratelist(1001, 0.200) # 피부
HF08 = ratelist(1001, 0.000) # 눈
HF09 = ratelist(1001, 0.000) # 위/소화
HF10 = ratelist(1001, 0.500) # 장건강
HF11 = ratelist(1001, 0.000) # 비뇨
HF12 = ratelist(1001, 0.000) # 요로
HF13 = ratelist(1001, 0.000) # 전립선
HF14 = ratelist(1001, 0.000) # 남성
HF15 = ratelist(1001, 0.000) # 여성 갱년기
HF16 = ratelist(1001, 0.000) # 여성
HF17 = ratelist(1001, 0.000) # 운동
HF18 = ratelist(1001, 0.000) # 체지방
HF19 = ratelist(1001, 0.000) # 스트레스/수면
HF20 = ratelist(1001, 0.500) # 두뇌
HF21 = ratelist(1001, 0.800) # 어린이 성장
HF22 = ratelist(1001, 0.000) # 혈당
HF23 = ratelist(1001, 0.000) # 혈압
HF24 = ratelist(1001, 0.000) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.005) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.013) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.010) # 위장관
DI02 = ratelist(1001, 0.010) # 간
DI03 = ratelist(1001, 0.010) # 심혈관계
DI04 = ratelist(1001, 0.010) # 신장
DI05 = ratelist(1001, 0.005) # 당뇨
DI06 = ratelist(1001, 0.010) # 고혈압
DI07 = ratelist(1001, 0.010) # 고지혈증
DI08 = ratelist(1001, 0.000) # 혈액응고장애
DI09 = ratelist(1001, 0.010) # 갑상선
DI10 = ratelist(1001, 0.010) # 천식
DI11 = ratelist(1001, 0.005) # 담낭
DI12 = ratelist(1001, 0.010) # 자가면역
DI13 = ratelist(1001, 0.010) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.010) # 수술 여부
survey_alcohol = ratelist(1001, 0.000)   # 음주 여부
survey_smoking = ratelist(1001, 0.000)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(00)
    survey_sex.append(1)

F_00 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_00

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [69]:
HF01 = ratelist(1001, 0.000) # 간
HF02 = ratelist(1001, 0.000) # 피로
HF03 = ratelist(1001, 0.000) # 뼈/관절
HF04 = ratelist(1001, 0.050) # 치아/구강
HF05 = ratelist(1001, 0.000) # 면역
HF06 = ratelist(1001, 0.000) # 노화/항산화
HF07 = ratelist(1001, 0.400) # 피부
HF08 = ratelist(1001, 0.000) # 눈
HF09 = ratelist(1001, 0.000) # 위/소화
HF10 = ratelist(1001, 0.500) # 장건강
HF11 = ratelist(1001, 0.000) # 비뇨
HF12 = ratelist(1001, 0.000) # 요로
HF13 = ratelist(1001, 0.000) # 전립선
HF14 = ratelist(1001, 0.000) # 남성
HF15 = ratelist(1001, 0.000) # 여성 갱년기
HF16 = ratelist(1001, 0.000) # 여성
HF17 = ratelist(1001, 0.300) # 운동
HF18 = ratelist(1001, 0.300) # 체지방
HF19 = ratelist(1001, 0.100) # 스트레스/수면
HF20 = ratelist(1001, 0.700) # 두뇌
HF21 = ratelist(1001, 0.300) # 어린이 성장
HF22 = ratelist(1001, 0.000) # 혈당
HF23 = ratelist(1001, 0.000) # 혈압
HF24 = ratelist(1001, 0.000) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.005) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.013) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.010) # 위장관
DI02 = ratelist(1001, 0.010) # 간
DI03 = ratelist(1001, 0.010) # 심혈관계
DI04 = ratelist(1001, 0.010) # 신장
DI05 = ratelist(1001, 0.005) # 당뇨
DI06 = ratelist(1001, 0.010) # 고혈압
DI07 = ratelist(1001, 0.010) # 고지혈증
DI08 = ratelist(1001, 0.000) # 혈액응고장애
DI09 = ratelist(1001, 0.010) # 갑상선
DI10 = ratelist(1001, 0.010) # 천식
DI11 = ratelist(1001, 0.005) # 담낭
DI12 = ratelist(1001, 0.010) # 자가면역
DI13 = ratelist(1001, 0.010) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.000) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.010) # 수술 여부
survey_alcohol = ratelist(1001, 0.000)   # 음주 여부
survey_smoking = ratelist(1001, 0.000)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(10)
    survey_sex.append(1)

F_10 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_10

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,10,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,10,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
998,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
HF01 = ratelist(1001, 0.162*0.15) # 간
HF02 = ratelist(1001, 0.434*0.698) # 피로
HF03 = ratelist(1001, 0.000*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.054*0.023) # 치아/구강
HF05 = ratelist(1001, 0.188*1) # 면역
HF06 = ratelist(1001, 0.115*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.608*0.268) # 피부
HF08 = ratelist(1001, 0.000*0.265) # 눈
HF09 = ratelist(1001, 0.098*0.008) # 위/소화
HF10 = ratelist(1001, 0.341*0.322) # 장건강
HF11 = ratelist(1001, 0.037*0.005) # 비뇨
HF12 = ratelist(1001, 0.086*0.005) # 요로
HF13 = ratelist(1001, 0.000*0.031) # 전립선
HF14 = ratelist(1001, 0.000*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.516*0.407) # 여성
HF17 = ratelist(1001, 0.318*0.465) # 운동
HF18 = ratelist(1001, 0.381*0.188) # 체지방
HF19 = ratelist(1001, 0.376*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.006*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.006*0.058) # 혈당
HF23 = ratelist(1001, 0.016*0.037) # 혈압
HF24 = ratelist(1001, 0.048*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.341) # 위장관
DI02 = ratelist(1001, 0.162) # 간
DI03 = ratelist(1001, 0.016) # 심혈관계
DI04 = ratelist(1001, 0.017) # 신장
DI05 = ratelist(1001, 0.006) # 당뇨
DI06 = ratelist(1001, 0.016) # 고혈압
DI07 = ratelist(1001, 0.048) # 고지혈증
DI08 = ratelist(1001, 0.000) # 혈액응고장애
DI09 = ratelist(1001, 0.025) # 갑상선
DI10 = ratelist(1001, 0.030) # 천식
DI11 = ratelist(1001, 0.004) # 담낭
DI12 = ratelist(1001, 0.012) # 자가면역
DI13 = ratelist(1001, 0.111) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.050) # 호르몬제

survey_pregnancy = ratelist(1001, 0.014) # 임신 여부
survey_operation = ratelist(1001, 0.015) # 수술 여부
survey_alcohol = ratelist(1001, 0.612)   # 음주 여부
survey_smoking = ratelist(1001, 0.094)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(20)
    survey_sex.append(1)

F_20 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_20

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,20,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,20,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,20,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
996,20,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,20,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,20,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,20,1,0,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
HF01 = ratelist(1001, 0.194*0.15) # 간
HF02 = ratelist(1001, 0.507*0.698) # 피로
HF03 = ratelist(1001, 0.000*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.060*0.023) # 치아/구강
HF05 = ratelist(1001, 0.345*1) # 면역
HF06 = ratelist(1001, 0.208*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.567*0.268) # 피부
HF08 = ratelist(1001, 0.031*0.265) # 눈
HF09 = ratelist(1001, 0.110*0.008) # 위/소화
HF10 = ratelist(1001, 0.334*0.322) # 장건강
HF11 = ratelist(1001, 0.048*0.005) # 비뇨
HF12 = ratelist(1001, 0.086*0.005) # 요로
HF13 = ratelist(1001, 0.000*0.031) # 전립선
HF14 = ratelist(1001, 0.000*0.005) # 남성
HF15 = ratelist(1001, 0.000*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.522*0.407) # 여성
HF17 = ratelist(1001, 0.276*0.465) # 운동
HF18 = ratelist(1001, 0.393*0.188) # 체지방
HF19 = ratelist(1001, 0.382*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.029*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.020*0.058) # 혈당
HF23 = ratelist(1001, 0.020*0.037) # 혈압
HF24 = ratelist(1001, 0.095*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.334) # 위장관
DI02 = ratelist(1001, 0.194) # 간
DI03 = ratelist(1001, 0.020) # 심혈관계
DI04 = ratelist(1001, 0.036) # 신장
DI05 = ratelist(1001, 0.020) # 당뇨
DI06 = ratelist(1001, 0.020) # 고혈압
DI07 = ratelist(1001, 0.095) # 고지혈증
DI08 = ratelist(1001, 0.005) # 혈액응고장애
DI09 = ratelist(1001, 0.027) # 갑상선
DI10 = ratelist(1001, 0.033) # 천식
DI11 = ratelist(1001, 0.010) # 담낭
DI12 = ratelist(1001, 0.012) # 자가면역
DI13 = ratelist(1001, 0.095) # 신경/정신계
DI14 = ratelist(1001, 0.001) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.050) # 호르몬제

survey_pregnancy = ratelist(1001, 0.059) # 임신 여부
survey_operation = ratelist(1001, 0.048) # 수술 여부
survey_alcohol = ratelist(1001, 0.532)   # 음주 여부
survey_smoking = ratelist(1001, 0.097)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(30)
    survey_sex.append(1)

F_30 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_30

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,30,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,30,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,30,1,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,30,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,30,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,30,1,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,30,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,30,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,30,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,30,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
HF01 = ratelist(1001, 0.205*0.15) # 간
HF02 = ratelist(1001, 0.477*0.698) # 피로
HF03 = ratelist(1001, 0.154*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.049*0.023) # 치아/구강
HF05 = ratelist(1001, 0.338*1) # 면역
HF06 = ratelist(1001, 0.137*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.316*0.268) # 피부
HF08 = ratelist(1001, 0.130*0.265) # 눈
HF09 = ratelist(1001, 0.161*0.008) # 위/소화
HF10 = ratelist(1001, 0.291*0.322) # 장건강
HF11 = ratelist(1001, 0.093*0.005) # 비뇨
HF12 = ratelist(1001, 0.086*0.005) # 요로
HF13 = ratelist(1001, 0.000*0.031) # 전립선
HF14 = ratelist(1001, 0.000*0.005) # 남성
HF15 = ratelist(1001, 0.080*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.384*0.407) # 여성
HF17 = ratelist(1001, 0.222*0.465) # 운동
HF18 = ratelist(1001, 0.424*0.188) # 체지방
HF19 = ratelist(1001, 0.423*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.160*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.068*0.058) # 혈당
HF23 = ratelist(1001, 0.134*0.037) # 혈압
HF24 = ratelist(1001, 0.150*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.291) # 위장관
DI02 = ratelist(1001, 0.205) # 간
DI03 = ratelist(1001, 0.134) # 심혈관계
DI04 = ratelist(1001, 0.065) # 신장
DI05 = ratelist(1001, 0.068) # 당뇨
DI06 = ratelist(1001, 0.134) # 고혈압
DI07 = ratelist(1001, 0.150) # 고지혈증
DI08 = ratelist(1001, 0.011) # 혈액응고장애
DI09 = ratelist(1001, 0.038) # 갑상선
DI10 = ratelist(1001, 0.016) # 천식
DI11 = ratelist(1001, 0.014) # 담낭
DI12 = ratelist(1001, 0.044) # 자가면역
DI13 = ratelist(1001, 0.067) # 신경/정신계
DI14 = ratelist(1001, 0.006) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.050) # 호르몬제

survey_pregnancy = ratelist(1001, 0.004) # 임신 여부
survey_operation = ratelist(1001, 0.026) # 수술 여부
survey_alcohol = ratelist(1001, 0.521)   # 음주 여부
survey_smoking = ratelist(1001, 0.067)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(40)
    survey_sex.append(1)

F_40 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_40

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,40,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,40,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,40,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,40,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,40,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,40,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
996,40,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
997,40,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,40,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,40,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
HF01 = ratelist(1001, 0.199*0.15) # 간
HF02 = ratelist(1001, 0.374*0.698) # 피로
HF03 = ratelist(1001, 0.328*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.055*0.023) # 치아/구강
HF05 = ratelist(1001, 0.424*1) # 면역
HF06 = ratelist(1001, 0.192*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.344*0.268) # 피부
HF08 = ratelist(1001, 0.160*0.265) # 눈
HF09 = ratelist(1001, 0.210*0.008) # 위/소화
HF10 = ratelist(1001, 0.390*0.322) # 장건강
HF11 = ratelist(1001, 0.158*0.005) # 비뇨
HF12 = ratelist(1001, 0.087*0.005) # 요로
HF13 = ratelist(1001, 0.000*0.031) # 전립선
HF14 = ratelist(1001, 0.000*0.005) # 남성
HF15 = ratelist(1001, 0.580*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.229*0.407) # 여성
HF17 = ratelist(1001, 0.245*0.465) # 운동
HF18 = ratelist(1001, 0.355*0.188) # 체지방
HF19 = ratelist(1001, 0.387*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.406*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.101*0.058) # 혈당
HF23 = ratelist(1001, 0.265*0.037) # 혈압
HF24 = ratelist(1001, 0.383*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.210) # 위장관
DI02 = ratelist(1001, 0.199) # 간
DI03 = ratelist(1001, 0.265) # 심혈관계
DI04 = ratelist(1001, 0.097) # 신장
DI05 = ratelist(1001, 0.101) # 당뇨
DI06 = ratelist(1001, 0.265) # 고혈압
DI07 = ratelist(1001, 0.383) # 고지혈증
DI08 = ratelist(1001, 0.031) # 혈액응고장애
DI09 = ratelist(1001, 0.073) # 갑상선
DI10 = ratelist(1001, 0.027) # 천식
DI11 = ratelist(1001, 0.025) # 담낭
DI12 = ratelist(1001, 0.044) # 자가면역
DI13 = ratelist(1001, 0.083) # 신경/정신계
DI14 = ratelist(1001, 0.006) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.050) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.031) # 수술 여부
survey_alcohol = ratelist(1001, 0.407)   # 음주 여부
survey_smoking = ratelist(1001, 0.063)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(50)
    survey_sex.append(1)

F_50 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_50

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,50,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,50,1,0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,50,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,50,1,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,50,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,50,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
996,50,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
997,50,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,50,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,50,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0

In [74]:
HF01 = ratelist(1001, 0.193*0.15) # 간
HF02 = ratelist(1001, 0.229*0.698) # 피로
HF03 = ratelist(1001, 0.652*0.501) # 뼈/관절
HF04 = ratelist(1001, 0.046*0.023) # 치아/구강
HF05 = ratelist(1001, 0.492*1) # 면역
HF06 = ratelist(1001, 0.165*0.881) # 노화/항산화
HF07 = ratelist(1001, 0.167*0.268) # 피부
HF08 = ratelist(1001, 0.228*0.265) # 눈
HF09 = ratelist(1001, 0.213*0.008) # 위/소화
HF10 = ratelist(1001, 0.359*0.322) # 장건강
HF11 = ratelist(1001, 0.232*0.005) # 비뇨
HF12 = ratelist(1001, 0.132*0.008) # 요로
HF13 = ratelist(1001, 0.000*0.031) # 전립선
HF14 = ratelist(1001, 0.000*0.005) # 남성
HF15 = ratelist(1001, 0.335*0.049) # 여성 갱년기
HF16 = ratelist(1001, 0.000*0.407) # 여성
HF17 = ratelist(1001, 0.237*0.465) # 운동
HF18 = ratelist(1001, 0.347*0.188) # 체지방
HF19 = ratelist(1001, 0.374*0.046) # 스트레스/수면
HF20 = ratelist(1001, 0.636*0.294) # 두뇌
HF21 = ratelist(1001, 0.000*0) # 어린이 성장
HF22 = ratelist(1001, 0.209*0.058) # 혈당
HF23 = ratelist(1001, 0.455*0.037) # 혈압
HF24 = ratelist(1001, 0.502*0.77) # 혈관/혈액순환

AL01 = ratelist(1001, 0.002) # 갑각류
AL02 = ratelist(1001, 0.001) # 옻
AL03 = ratelist(1001, 0.001) # 땅콩
AL04 = ratelist(1001, 0.001) # 프로폴리스
AL05 = ratelist(1001, 0.001) # 대두/대두단백
AL06 = ratelist(1001, 0.001) # 에스트로겐/이소플라본
AL07 = ratelist(1001, 0.001) # 우유/유제품
AL08 = ratelist(1001, 0.001) # 소맥
AL09 = ratelist(1001, 0.001) # 호프
AL10 = ratelist(1001, 0.001) # 호박씨
AL11 = ratelist(1001, 0.001) # 홍삼
AL12 = ratelist(1001, 0.001) # 사상자
AL13 = ratelist(1001, 0.001) # 산수유
AL14 = ratelist(1001, 0.001) # 무화과
AL15 = ratelist(1001, 0.001) # 사과
AL16 = ratelist(1001, 0.001) # 국화과
AL17 = ratelist(1001, 0.001) # 난황
AL18 = ratelist(1001, 0.001) # 달맞이꽃종자유
AL19 = ratelist(1001, 0.001) # 석류
AL20 = ratelist(1001, 0.001) # 강황

DI01 = ratelist(1001, 0.359) # 위장관
DI02 = ratelist(1001, 0.193) # 간
DI03 = ratelist(1001, 0.455) # 심혈관계
DI04 = ratelist(1001, 0.189) # 신장
DI05 = ratelist(1001, 0.209) # 당뇨
DI06 = ratelist(1001, 0.455) # 고혈압
DI07 = ratelist(1001, 0.502) # 고지혈증
DI08 = ratelist(1001, 0.050) # 혈액응고장애
DI09 = ratelist(1001, 0.029) # 갑상선
DI10 = ratelist(1001, 0.037) # 천식
DI11 = ratelist(1001, 0.037) # 담낭
DI12 = ratelist(1001, 0.076) # 자가면역
DI13 = ratelist(1001, 0.078) # 신경/정신계
DI14 = ratelist(1001, 0.011) # 암
DI15 = ratelist(1001, 0.001) # 단장증후군/유당불내증
DI16 = ratelist(1001, 0.001) # 피부 광과민성
DI17 = ratelist(1001, 0.050) # 호르몬제

survey_pregnancy = ratelist(1001, 0.000) # 임신 여부
survey_operation = ratelist(1001, 0.073) # 수술 여부
survey_alcohol = ratelist(1001, 0.283)   # 음주 여부
survey_smoking = ratelist(1001, 0.036)   # 흡연 여부

survey_age_group = []
survey_sex = []
for i in range (1, 1001):
    survey_age_group.append(60)
    survey_sex.append(1)

F_60 = pd.DataFrame({
    'survey_age_group':survey_age_group, 'survey_sex':survey_sex,
    'survey_pregnancy':survey_pregnancy, 'survey_operation':survey_operation,
    'survey_alcohol':survey_alcohol, 'survey_smoking':survey_smoking,
    'HF01':HF01, 'HF02':HF02, 'HF03':HF03, 'HF04':HF04, 'HF05':HF05,
    'HF06':HF06, 'HF07':HF07, 'HF08':HF08, 'HF09':HF09, 'HF10':HF10, 
    'HF11':HF11, 'HF12':HF12, 'HF13':HF13, 'HF14':HF14, 'HF15':HF15,
    'HF16':HF16, 'HF17':HF17, 'HF18':HF18, 'HF19':HF19, 'HF20':HF20,
    'HF21':HF21, 'HF22':HF22, 'HF23':HF23, 'HF24':HF24,
    'AL01':AL01, 'AL02':AL02, 'AL03':AL03, 'AL04':AL04, 'AL05':AL05,
    'AL06':AL06, 'AL07':AL07, 'AL08':AL08, 'AL09':AL09, 'AL10':AL10, 
    'AL11':AL11, 'AL12':AL12, 'AL13':AL13, 'AL14':AL14, 'AL15':AL15,
    'AL16':AL16, 'AL17':AL17, 'AL18':AL18, 'AL19':AL19, 'AL20':AL20,
    'DI01':DI01, 'DI02':DI02, 'DI03':DI03, 'DI04':DI04, 'DI05':DI05,
    'DI06':DI06, 'DI07':DI07, 'DI08':DI08, 'DI09':DI09, 'DI10':DI10, 
    'DI11':DI11, 'DI12':DI12, 'DI13':DI13, 'DI14':DI14, 'DI15':DI15,
    'DI16':DI16, 'DI17':DI17
})

F_60

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
0,60,1,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,60,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,60,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,60,1,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,60,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
996,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
997,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,60,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [75]:
dummy1 = pd.concat([M_00, M_10, M_20, M_30, M_40, M_50, M_60, F_00, F_10, F_20, F_30, F_40, F_50, F_60], ignore_index=True)
print(dummy1.describe().T.to_string())

                    count       mean        std  min   25%   50%   75%   max
survey_age_group  14000.0  30.000000  20.000714  0.0  10.0  30.0  50.0  60.0
survey_sex        14000.0   0.500000   0.500018  0.0   0.0   0.5   1.0   1.0
survey_pregnancy  14000.0   0.005500   0.073960  0.0   0.0   0.0   0.0   1.0
survey_operation  14000.0   0.026714   0.161253  0.0   0.0   0.0   0.0   1.0
survey_alcohol    14000.0   0.414643   0.492678  0.0   0.0   0.0   1.0   1.0
survey_smoking    14000.0   0.157429   0.364217  0.0   0.0   0.0   0.0   1.0
HF01              14000.0   0.022286   0.147616  0.0   0.0   0.0   0.0   1.0
HF02              14000.0   0.198357   0.398777  0.0   0.0   0.0   0.0   1.0
HF03              14000.0   0.051143   0.220297  0.0   0.0   0.0   0.0   1.0
HF04              14000.0   0.022286   0.147616  0.0   0.0   0.0   0.0   1.0
HF05              14000.0   0.217714   0.412707  0.0   0.0   0.0   0.0   1.0
HF06              14000.0   0.087643   0.282785  0.0   0.0   0.0   0.0   1.0
HF07              14000.0   0.132214   0.338736  0.0   0.0   0.0   0.0   1.0
HF08              14000.0   0.022500   0.148308  0.0   0.0   0.0   0.0   1.0
HF09              14000.0   0.000429   0.020698  0.0   0.0   0.0   0.0   1.0
HF10              14000.0   0.212571   0.409142  0.0   0.0   0.0   0.0   1.0
HF11              14000.0   0.000143   0.011952  0.0   0.0   0.0   0.0   1.0
HF12              14000.0   0.000071   0.008452  0.0   0.0   0.0   0.0   1.0
HF13              14000.0   0.002571   0.050646  0.0   0.0   0.0   0.0   1.0
HF14              14000.0   0.000071   0.008452  0.0   0.0   0.0   0.0   1.0
HF15              14000.0   0.003357   0.057846  0.0   0.0   0.0   0.0   1.0
HF16              14000.0   0.047929   0.213623  0.0   0.0   0.0   0.0   1.0
HF17              14000.0   0.126571   0.332504  0.0   0.0   0.0   0.0   1.0
HF18              14000.0   0.080500   0.272075  0.0   0.0   0.0   0.0   1.0
HF19              14000.0   0.026071   0.159353  0.0   0.0   0.0   0.0   1.0
HF20              14000.0   0.223143   0.416368  0.0   0.0   0.0   0.0   1.0
HF21              14000.0   0.142857   0.349940  0.0   0.0   0.0   0.0   1.0
HF22              14000.0   0.004214   0.064783  0.0   0.0   0.0   0.0   1.0
HF23              14000.0   0.005429   0.073481  0.0   0.0   0.0   0.0   1.0
HF24              14000.0   0.128500   0.334658  0.0   0.0   0.0   0.0   1.0
AL01              14000.0   0.002000   0.044678  0.0   0.0   0.0   0.0   1.0
AL02              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL03              14000.0   0.002143   0.046243  0.0   0.0   0.0   0.0   1.0
AL04              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL05              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL06              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL07              14000.0   0.004429   0.066402  0.0   0.0   0.0   0.0   1.0
AL08              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL09              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL10              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL11              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL12              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL13              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL14              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL15              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL16              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL17              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL18              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL19              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL20              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI01              14000.0   0.210214   0.407475  0.0   0.0   0.0   0.0   1.0
DI02              14000.0   0.153500   0.360482  0.0   0.0   0.0   0.0   1.0
DI03              14000.0   0.155643   0.362529  0.0   0.0   0.0   0.0   1.0
DI04              14000.0   0.063857   0.244507  0.0   0.0   0.0   0.0   1.0
DI05              14000.0   0.073786   0.261431  0.0   0.0   0.0   0.0   1.0
DI06              14000.0   0.155643   0.362529  0.0   0.0   0.0   0.0   1.0
DI07              14000.0   0.164143   0.370418  0.0   0.0   0.0   0.0   1.0
DI08              14000.0   0.017571   0.131392  0.0   0.0   0.0   0.0   1.0
DI09              14000.0   0.024571   0.154820  0.0   0.0   0.0   0.0   1.0
DI10              14000.0   0.023214   0.150589  0.0   0.0   0.0   0.0   1.0
DI11              14000.0   0.014286   0.118670  0.0   0.0   0.0   0.0   1.0
DI12              14000.0   0.020500   0.141708  0.0   0.0   0.0   0.0   1.0
DI13              14000.0   0.067071   0.250155  0.0   0.0   0.0   0.0   1.0
DI14              14000.0   0.004500   0.066933  0.0   0.0   0.0   0.0   1.0
DI15              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI16              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI17              14000.0   0.017857   0.132437  0.0   0.0   0.0   0.0   1.0

In [76]:
dummy_pregnant = dummy1[dummy1['survey_pregnancy'] == 1]
dummy_nonpreg = dummy1[dummy1['survey_pregnancy'] != 1]
dummy_pregnant

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI08,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17
9053,20,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9054,20,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9095,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9217,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9239,20,1,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10987,30,1,1,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,1
11444,40,1,1,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
11447,40,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11691,40,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11878,40,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
HF25 = ratelist(78, 0.900) # 임신/태아
survey_alcohol = ratelist(78, 0.014)
survey_smoking = ratelist(78, 0.011)
# survey_operation은 제왕절개를 계획하는 사람도 있을 수 있으므로 기존 값 유지

dummy_pregnant = dummy_pregnant.drop(['survey_alcohol', 'survey_smoking'], axis=1)

dummy_pregnant.insert(4, 'survey_alcohol', survey_alcohol)
dummy_pregnant.insert(5, 'survey_smoking', survey_smoking)
dummy_pregnant.insert(30, 'HF25', HF25)
print(dummy_pregnant.describe().T.to_string())

                  count       mean       std   min   25%   50%   75%   max
survey_age_group   77.0  28.701299  4.687792  20.0  30.0  30.0  30.0  40.0
survey_sex         77.0   1.000000  0.000000   1.0   1.0   1.0   1.0   1.0
survey_pregnancy   77.0   1.000000  0.000000   1.0   1.0   1.0   1.0   1.0
survey_operation   77.0   0.025974  0.160101   0.0   0.0   0.0   0.0   1.0
survey_alcohol     77.0   0.012987  0.113961   0.0   0.0   0.0   0.0   1.0
survey_smoking     77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF01               77.0   0.025974  0.160101   0.0   0.0   0.0   0.0   1.0
HF02               77.0   0.285714  0.454716   0.0   0.0   0.0   1.0   1.0
HF03               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF04               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF05               77.0   0.311688  0.466221   0.0   0.0   0.0   1.0   1.0
HF06               77.0   0.129870  0.338365   0.0   0.0   0.0   0.0   1.0
HF07               77.0   0.168831  0.377059   0.0   0.0   0.0   0.0   1.0
HF08               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF09               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF10               77.0   0.129870  0.338365   0.0   0.0   0.0   0.0   1.0
HF11               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF12               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF13               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF14               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF15               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF16               77.0   0.155844  0.365086   0.0   0.0   0.0   0.0   1.0
HF17               77.0   0.051948  0.223377   0.0   0.0   0.0   0.0   1.0
HF18               77.0   0.116883  0.323388   0.0   0.0   0.0   0.0   1.0
HF19               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF20               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF21               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF22               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF23               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
HF24               77.0   0.077922  0.269807   0.0   0.0   0.0   0.0   1.0
HF25               77.0   0.909091  0.289365   0.0   1.0   1.0   1.0   1.0
AL01               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL02               77.0   0.012987  0.113961   0.0   0.0   0.0   0.0   1.0
AL03               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL04               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL05               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL06               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL07               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL08               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL09               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL10               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL11               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL12               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL13               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL14               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL15               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL16               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL17               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL18               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL19               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
AL20               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
DI01               77.0   0.207792  0.408388   0.0   0.0   0.0   0.0   1.0
DI02               77.0   0.194805  0.398648   0.0   0.0   0.0   0.0   1.0
DI03               77.0   0.038961  0.194771   0.0   0.0   0.0   0.0   1.0
DI04               77.0   0.012987  0.113961   0.0   0.0   0.0   0.0   1.0
DI05               77.0   0.038961  0.194771   0.0   0.0   0.0   0.0   1.0
DI06               77.0   0.025974  0.160101   0.0   0.0   0.0   0.0   1.0
DI07               77.0   0.064935  0.248027   0.0   0.0   0.0   0.0   1.0
DI08               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
DI09               77.0   0.025974  0.160101   0.0   0.0   0.0   0.0   1.0
DI10               77.0   0.038961  0.194771   0.0   0.0   0.0   0.0   1.0
DI11               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
DI12               77.0   0.012987  0.113961   0.0   0.0   0.0   0.0   1.0
DI13               77.0   0.103896  0.307127   0.0   0.0   0.0   0.0   1.0
DI14               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
DI15               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
DI16               77.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
DI17               77.0   0.038961  0.194771   0.0   0.0   0.0   0.0   1.0

In [78]:
dummy2 = pd.concat([dummy_pregnant, dummy_nonpreg])
dummy2['HF25'] = dummy2['HF25'].fillna(0)
dummy2 = dummy2.astype({'HF25':'int64'})
dummy2 = dummy2.sort_index()

print(dummy2.describe().T.to_string())

                    count       mean        std  min   25%   50%   75%   max
survey_age_group  14000.0  30.000000  20.000714  0.0  10.0  30.0  50.0  60.0
survey_sex        14000.0   0.500000   0.500018  0.0   0.0   0.5   1.0   1.0
survey_pregnancy  14000.0   0.005500   0.073960  0.0   0.0   0.0   0.0   1.0
survey_operation  14000.0   0.026714   0.161253  0.0   0.0   0.0   0.0   1.0
survey_alcohol    14000.0   0.411571   0.492136  0.0   0.0   0.0   1.0   1.0
survey_smoking    14000.0   0.156857   0.363679  0.0   0.0   0.0   0.0   1.0
HF01              14000.0   0.022286   0.147616  0.0   0.0   0.0   0.0   1.0
HF02              14000.0   0.198357   0.398777  0.0   0.0   0.0   0.0   1.0
HF03              14000.0   0.051143   0.220297  0.0   0.0   0.0   0.0   1.0
HF04              14000.0   0.022286   0.147616  0.0   0.0   0.0   0.0   1.0
HF05              14000.0   0.217714   0.412707  0.0   0.0   0.0   0.0   1.0
HF06              14000.0   0.087643   0.282785  0.0   0.0   0.0   0.0   1.0
HF07              14000.0   0.132214   0.338736  0.0   0.0   0.0   0.0   1.0
HF08              14000.0   0.022500   0.148308  0.0   0.0   0.0   0.0   1.0
HF09              14000.0   0.000429   0.020698  0.0   0.0   0.0   0.0   1.0
HF10              14000.0   0.212571   0.409142  0.0   0.0   0.0   0.0   1.0
HF11              14000.0   0.000143   0.011952  0.0   0.0   0.0   0.0   1.0
HF12              14000.0   0.000071   0.008452  0.0   0.0   0.0   0.0   1.0
HF13              14000.0   0.002571   0.050646  0.0   0.0   0.0   0.0   1.0
HF14              14000.0   0.000071   0.008452  0.0   0.0   0.0   0.0   1.0
HF15              14000.0   0.003357   0.057846  0.0   0.0   0.0   0.0   1.0
HF16              14000.0   0.047929   0.213623  0.0   0.0   0.0   0.0   1.0
HF17              14000.0   0.126571   0.332504  0.0   0.0   0.0   0.0   1.0
HF18              14000.0   0.080500   0.272075  0.0   0.0   0.0   0.0   1.0
HF19              14000.0   0.026071   0.159353  0.0   0.0   0.0   0.0   1.0
HF20              14000.0   0.223143   0.416368  0.0   0.0   0.0   0.0   1.0
HF21              14000.0   0.142857   0.349940  0.0   0.0   0.0   0.0   1.0
HF22              14000.0   0.004214   0.064783  0.0   0.0   0.0   0.0   1.0
HF23              14000.0   0.005429   0.073481  0.0   0.0   0.0   0.0   1.0
HF24              14000.0   0.128500   0.334658  0.0   0.0   0.0   0.0   1.0
HF25              14000.0   0.005000   0.070536  0.0   0.0   0.0   0.0   1.0
AL01              14000.0   0.002000   0.044678  0.0   0.0   0.0   0.0   1.0
AL02              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL03              14000.0   0.002143   0.046243  0.0   0.0   0.0   0.0   1.0
AL04              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL05              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL06              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL07              14000.0   0.004429   0.066402  0.0   0.0   0.0   0.0   1.0
AL08              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL09              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL10              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL11              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL12              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL13              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL14              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL15              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL16              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL17              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL18              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL19              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL20              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI01              14000.0   0.210214   0.407475  0.0   0.0   0.0   0.0   1.0
DI02              14000.0   0.153500   0.360482  0.0   0.0   0.0   0.0   1.0
DI03              14000.0   0.155643   0.362529  0.0   0.0   0.0   0.0   1.0
DI04              14000.0   0.063857   0.244507  0.0   0.0   0.0   0.0   1.0
DI05              14000.0   0.073786   0.261431  0.0   0.0   0.0   0.0   1.0
DI06              14000.0   0.155643   0.362529  0.0   0.0   0.0   0.0   1.0
DI07              14000.0   0.164143   0.370418  0.0   0.0   0.0   0.0   1.0
DI08              14000.0   0.017571   0.131392  0.0   0.0   0.0   0.0   1.0
DI09              14000.0   0.024571   0.154820  0.0   0.0   0.0   0.0   1.0
DI10              14000.0   0.023214   0.150589  0.0   0.0   0.0   0.0   1.0
DI11              14000.0   0.014286   0.118670  0.0   0.0   0.0   0.0   1.0
DI12              14000.0   0.020500   0.141708  0.0   0.0   0.0   0.0   1.0
DI13              14000.0   0.067071   0.250155  0.0   0.0   0.0   0.0   1.0
DI14              14000.0   0.004500   0.066933  0.0   0.0   0.0   0.0   1.0
DI15              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI16              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI17              14000.0   0.017857   0.132437  0.0   0.0   0.0   0.0   1.0

In [79]:
dummy2['HF_sum'] = dummy2[[
    'HF01', 'HF02', 'HF03', 'HF04', 'HF05', 'HF06', 'HF07', 'HF08', 'HF09', 'HF10',
    'HF11', 'HF12', 'HF13', 'HF14', 'HF15', 'HF16', 'HF17', 'HF18', 'HF19', 'HF20',
    'HF21', 'HF22', 'HF23', 'HF24', 'HF25'
]].sum(axis=1)
dummy2_manyHF = dummy2[dummy2['HF_sum'] > 5]
dummy2_enoughHF = dummy2[dummy2['HF_sum'] <= 5]
dummy2

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17,HF_sum
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13995,60,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
13996,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2
13997,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
13998,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
13999,60,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [80]:
index_list = dummy2_manyHF.index.values.tolist()
dummy2_manyHF_removed = pd.DataFrame(columns = [
    'survey_age_group', 'survey_sex', 'survey_pregnancy',
    'survey_operation', 'survey_alcohol', 'survey_smoking',
    'HF01', 'HF02', 'HF03', 'HF04', 'HF05', 'HF06', 'HF07', 'HF08', 'HF09', 'HF10',
    'HF11', 'HF12', 'HF13', 'HF14', 'HF15', 'HF16', 'HF17', 'HF18', 'HF19', 'HF20',
    'HF21', 'HF22', 'HF23', 'HF24', 'HF25',
    'AL01', 'AL02', 'AL03', 'AL04', 'AL05', 'AL06', 'AL07', 'AL08', 'AL09', 'AL10',
    'AL11', 'AL12', 'AL13', 'AL14', 'AL15', 'AL16', 'AL17', 'AL18', 'AL19', 'AL20',
    'DI01', 'DI02', 'DI03', 'DI04', 'DI05', 'DI06', 'DI07', 'DI08', 'DI09', 'DI10',
    'DI11', 'DI12', 'DI13', 'DI14', 'DI15', 'DI16', 'DI17',
    'HF_sum'
])

for i in index_list:
    # 행을 list로 변환
    row_list = dummy2_manyHF.loc[i, :].values.flatten().tolist()

    # 관심있다고 선택한 건강고민의 위치를 list로 변환
    HF_interest = []
    for j in range(6,31):
        if row_list[j] == 1:
            HF_interest.append(j)
    
    # 관심있다고 선택한 건강고민의 위치 중 삭제할 것들 랜덤하게 선택
    removal_elements = random.sample(HF_interest, row_list[-1]-5)
    
    # 삭제될 것들 0으로 변경
    for k in removal_elements:
        row_list[k] = 0

    dummy2_manyHF_removed.loc[i] = row_list


dummy2_manyHF_removed['HF_sum'] = dummy2_manyHF_removed[[
    'HF01', 'HF02', 'HF03', 'HF04', 'HF05', 'HF06', 'HF07', 'HF08', 'HF09', 'HF10',
    'HF11', 'HF12', 'HF13', 'HF14', 'HF15', 'HF16', 'HF17', 'HF18', 'HF19', 'HF20',
    'HF21', 'HF22', 'HF23', 'HF24', 'HF25'
]].sum(axis=1)

dummy2_manyHF_removed = dummy2_manyHF_removed.astype({'HF24':'int64', 'HF25':'int64'})
dummy2_manyHF_removed

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17,HF_sum
4758,40,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
8191,10,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,5
8415,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
8491,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
8567,10,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5
8809,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
8838,10,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
9386,20,1,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,5
9824,20,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,5
10544,30,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,5
10608,30,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,5
10929,30,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,5
12132,50,1,0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,5
12674,50,1,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,5
12694,50,1,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,5
12783,50,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,5
12953,50,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,5
13058,60,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,5
13112,60,1,0,0,0,1,1,0,0,0,...,1,0,1,0,0,0,0,0,0,5
13226,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
13388,60,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
13616,60,1,0,0,0,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,5
13657,60,1,0,1,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,5
13803,60,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
13948,60,1,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,5

In [81]:
dummy3 = pd.concat([dummy2_enoughHF, dummy2_manyHF_removed])
dummy3 = dummy3.sort_index()
dummy3

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17,HF_sum
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13995,60,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
13996,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2
13997,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
13998,60,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
13999,60,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [82]:
for idx in dummy3.index:
    if dummy3['survey_sex'][idx] == 0:
        dummy3['survey_sex'][idx] = 'm'
    if dummy3['survey_sex'][idx] == 1:
        dummy3['survey_sex'][idx] = 'f'
    if dummy3['survey_pregnancy'][idx] == 0:
        dummy3['survey_pregnancy'][idx] = 'P0'
    if dummy3['survey_pregnancy'][idx] == 1:
        if random.choices([1,2,3], [0.05, 0.05, 0.9]) == [1]:
            dummy3['survey_pregnancy'][idx] = 'P1'
        if random.choices([1,2,3], [0.05, 0.05, 0.9]) == [2]:
            dummy3['survey_pregnancy'][idx] = 'P2'
        if random.choices([1,2,3], [0.05, 0.05, 0.9]) == [3]:
            dummy3['survey_pregnancy'][idx] = 'P3'
    if dummy3['survey_operation'][idx] == 0:
        dummy3['survey_operation'][idx] = 'O0'
    if dummy3['survey_operation'][idx] == 1:
        if random.choices([1,2,3], [0.05, 0.05, 0.9]) == [1]:
            dummy3['survey_operation'][idx] = 'O1'
        if random.choices([1,2,3], [0.05, 0.05, 0.9]) == [2]:
            dummy3['survey_operation'][idx] = 'O2'
        if random.choices([1,2,3], [0.05, 0.05, 0.9]) == [3]:
            dummy3['survey_operation'][idx] = 'O3'
    if dummy3['survey_alcohol'][idx] == 0:
        dummy3['survey_alcohol'][idx] = 'A0'
    if dummy3['survey_alcohol'][idx] == 1:
        if random.choices([1,2,3], [0.5, 0.3, 0.2]) == [1]:
            dummy3['survey_alcohol'][idx] = 'A1'
        if random.choices([1,2,3], [0.5, 0.3, 0.2]) == [2]:
            dummy3['survey_alcohol'][idx] = 'A2'
        if random.choices([1,2,3], [0.5, 0.3, 0.2]) == [3]:
            dummy3['survey_alcohol'][idx] = 'A3'
    if dummy3['survey_smoking'][idx] == 0:
        dummy3['survey_smoking'][idx] = 'n'
    if dummy3['survey_smoking'][idx] == 1:
        dummy3['survey_smoking'][idx] = 'y'

C:\Users\Dreamliner\AppData\Local\Temp\ipykernel_44968\2078945303.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dummy3['survey_pregnancy'][idx] = 'P0'
C:\Users\Dreamliner\AppData\Local\Temp\ipykernel_44968\2078945303.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dummy3['survey_operation'][idx] = 'O0'
C:\Users\Dreamliner\AppData\Local\Temp\ipykernel_44968\2078945303.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dummy3['survey_alcohol'][idx] = 'A0'
C:\Users\Dreamliner\AppData\Local\Temp\ipykernel_44968\2078945303.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dummy3['survey_smoking'][idx] = 'n'

In [83]:
dummy3

,survey_age_group,survey_sex,survey_pregnancy,survey_operation,survey_alcohol,survey_smoking,HF01,HF02,HF03,HF04,...,DI09,DI10,DI11,DI12,DI13,DI14,DI15,DI16,DI17,HF_sum
0,0,m,P0,O0,A0,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,m,P0,O0,A0,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,0,m,P0,O3,A0,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,m,P0,O0,A0,n,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2
4,0,m,P0,O0,A0,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13995,60,f,P0,O0,A0,n,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
13996,60,f,P0,O0,A0,n,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2
13997,60,f,P0,O0,A0,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
13998,60,f,P0,O0,A0,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
13999,60,f,P0,O0,A1,n,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [84]:
dummy3.to_csv('data/dummy_survey_240625_v1.csv', index=False, encoding='utf-8-sig')
dummy3.to_pickle('data/dummy_survey_240625_v1.pkl')

In [85]:
print(dummy3.describe().T.to_string())

                    count       mean        std  min   25%   50%   75%   max
survey_age_group  14000.0  30.000000  20.000714  0.0  10.0  30.0  50.0  60.0
HF01              14000.0   0.022143   0.147153  0.0   0.0   0.0   0.0   1.0
HF02              14000.0   0.198071   0.398561  0.0   0.0   0.0   0.0   1.0
HF03              14000.0   0.051071   0.220151  0.0   0.0   0.0   0.0   1.0
HF04              14000.0   0.022286   0.147616  0.0   0.0   0.0   0.0   1.0
HF05              14000.0   0.217500   0.412560  0.0   0.0   0.0   0.0   1.0
HF06              14000.0   0.087571   0.282681  0.0   0.0   0.0   0.0   1.0
HF07              14000.0   0.132000   0.338503  0.0   0.0   0.0   0.0   1.0
HF08              14000.0   0.022500   0.148308  0.0   0.0   0.0   0.0   1.0
HF09              14000.0   0.000429   0.020698  0.0   0.0   0.0   0.0   1.0
HF10              14000.0   0.212500   0.409091  0.0   0.0   0.0   0.0   1.0
HF11              14000.0   0.000143   0.011952  0.0   0.0   0.0   0.0   1.0
HF12              14000.0   0.000071   0.008452  0.0   0.0   0.0   0.0   1.0
HF13              14000.0   0.002571   0.050646  0.0   0.0   0.0   0.0   1.0
HF14              14000.0   0.000071   0.008452  0.0   0.0   0.0   0.0   1.0
HF15              14000.0   0.003357   0.057846  0.0   0.0   0.0   0.0   1.0
HF16              14000.0   0.047857   0.213472  0.0   0.0   0.0   0.0   1.0
HF17              14000.0   0.126357   0.332263  0.0   0.0   0.0   0.0   1.0
HF18              14000.0   0.080071   0.271413  0.0   0.0   0.0   0.0   1.0
HF19              14000.0   0.026071   0.159353  0.0   0.0   0.0   0.0   1.0
HF20              14000.0   0.223143   0.416368  0.0   0.0   0.0   0.0   1.0
HF21              14000.0   0.142857   0.349940  0.0   0.0   0.0   0.0   1.0
HF22              14000.0   0.004143   0.064234  0.0   0.0   0.0   0.0   1.0
HF23              14000.0   0.005429   0.073481  0.0   0.0   0.0   0.0   1.0
HF24              14000.0   0.128357   0.334499  0.0   0.0   0.0   0.0   1.0
HF25              14000.0   0.005000   0.070536  0.0   0.0   0.0   0.0   1.0
AL01              14000.0   0.002000   0.044678  0.0   0.0   0.0   0.0   1.0
AL02              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL03              14000.0   0.002143   0.046243  0.0   0.0   0.0   0.0   1.0
AL04              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL05              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL06              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL07              14000.0   0.004429   0.066402  0.0   0.0   0.0   0.0   1.0
AL08              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL09              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL10              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL11              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL12              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL13              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL14              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL15              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL16              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL17              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL18              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL19              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
AL20              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI01              14000.0   0.210214   0.407475  0.0   0.0   0.0   0.0   1.0
DI02              14000.0   0.153500   0.360482  0.0   0.0   0.0   0.0   1.0
DI03              14000.0   0.155643   0.362529  0.0   0.0   0.0   0.0   1.0
DI04              14000.0   0.063857   0.244507  0.0   0.0   0.0   0.0   1.0
DI05              14000.0   0.073786   0.261431  0.0   0.0   0.0   0.0   1.0
DI06              14000.0   0.155643   0.362529  0.0   0.0   0.0   0.0   1.0
DI07              14000.0   0.164143   0.370418  0.0   0.0   0.0   0.0   1.0
DI08              14000.0   0.017571   0.131392  0.0   0.0   0.0   0.0   1.0
DI09              14000.0   0.024571   0.154820  0.0   0.0   0.0   0.0   1.0
DI10              14000.0   0.023214   0.150589  0.0   0.0   0.0   0.0   1.0
DI11              14000.0   0.014286   0.118670  0.0   0.0   0.0   0.0   1.0
DI12              14000.0   0.020500   0.141708  0.0   0.0   0.0   0.0   1.0
DI13              14000.0   0.067071   0.250155  0.0   0.0   0.0   0.0   1.0
DI14              14000.0   0.004500   0.066933  0.0   0.0   0.0   0.0   1.0
DI15              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI16              14000.0   0.001000   0.031608  0.0   0.0   0.0   0.0   1.0
DI17              14000.0   0.017857   0.132437  0.0   0.0   0.0   0.0   1.0
HF_sum            14000.0   1.761571   1.166481  0.0   1.0   2.0   3.0   5.0